//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShipCaddieApp.ShipCaddieAppXml {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShipmentModelIntegration", Namespace="http://schemas.datacontract.org/2004/07/ShipCaddieAPIInterface")]
    [System.SerializableAttribute()]
    public partial class ShipmentModelIntegration : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ShipCaddieApp.ShipCaddieAppXml.Addressfrom addressFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ShipCaddieApp.ShipCaddieAppXml.Addressto addressToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ShipCaddieApp.ShipCaddieAppXml.Carrier[] carriersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateShippedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ShipCaddieApp.ShipCaddieAppXml.Package[] packagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string printFormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int shipmentIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ShipCaddieApp.ShipCaddieAppXml.Addressfrom addressFrom {
            get {
                return this.addressFromField;
            }
            set {
                if ((object.ReferenceEquals(this.addressFromField, value) != true)) {
                    this.addressFromField = value;
                    this.RaisePropertyChanged("addressFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ShipCaddieApp.ShipCaddieAppXml.Addressto addressTo {
            get {
                return this.addressToField;
            }
            set {
                if ((object.ReferenceEquals(this.addressToField, value) != true)) {
                    this.addressToField = value;
                    this.RaisePropertyChanged("addressTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ShipCaddieApp.ShipCaddieAppXml.Carrier[] carriers {
            get {
                return this.carriersField;
            }
            set {
                if ((object.ReferenceEquals(this.carriersField, value) != true)) {
                    this.carriersField = value;
                    this.RaisePropertyChanged("carriers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dateShipped {
            get {
                return this.dateShippedField;
            }
            set {
                if ((this.dateShippedField.Equals(value) != true)) {
                    this.dateShippedField = value;
                    this.RaisePropertyChanged("dateShipped");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ShipCaddieApp.ShipCaddieAppXml.Package[] packages {
            get {
                return this.packagesField;
            }
            set {
                if ((object.ReferenceEquals(this.packagesField, value) != true)) {
                    this.packagesField = value;
                    this.RaisePropertyChanged("packages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string printFormat {
            get {
                return this.printFormatField;
            }
            set {
                if ((object.ReferenceEquals(this.printFormatField, value) != true)) {
                    this.printFormatField = value;
                    this.RaisePropertyChanged("printFormat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int shipmentId {
            get {
                return this.shipmentIdField;
            }
            set {
                if ((this.shipmentIdField.Equals(value) != true)) {
                    this.shipmentIdField = value;
                    this.RaisePropertyChanged("shipmentId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Addressfrom", Namespace="http://schemas.datacontract.org/2004/07/ShipCaddieAPIInterface")]
    [System.SerializableAttribute()]
    public partial class Addressfrom : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string address1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string address2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string attentionOfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string companyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string countryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isResidentialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int systemCountryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string zipCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address1 {
            get {
                return this.address1Field;
            }
            set {
                if ((object.ReferenceEquals(this.address1Field, value) != true)) {
                    this.address1Field = value;
                    this.RaisePropertyChanged("address1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address2 {
            get {
                return this.address2Field;
            }
            set {
                if ((object.ReferenceEquals(this.address2Field, value) != true)) {
                    this.address2Field = value;
                    this.RaisePropertyChanged("address2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string attentionOf {
            get {
                return this.attentionOfField;
            }
            set {
                if ((object.ReferenceEquals(this.attentionOfField, value) != true)) {
                    this.attentionOfField = value;
                    this.RaisePropertyChanged("attentionOf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string city {
            get {
                return this.cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cityField, value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string companyName {
            get {
                return this.companyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.companyNameField, value) != true)) {
                    this.companyNameField = value;
                    this.RaisePropertyChanged("companyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string countryCode {
            get {
                return this.countryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.countryCodeField, value) != true)) {
                    this.countryCodeField = value;
                    this.RaisePropertyChanged("countryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isResidential {
            get {
                return this.isResidentialField;
            }
            set {
                if ((this.isResidentialField.Equals(value) != true)) {
                    this.isResidentialField = value;
                    this.RaisePropertyChanged("isResidential");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneNumberField, value) != true)) {
                    this.phoneNumberField = value;
                    this.RaisePropertyChanged("phoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string state {
            get {
                return this.stateField;
            }
            set {
                if ((object.ReferenceEquals(this.stateField, value) != true)) {
                    this.stateField = value;
                    this.RaisePropertyChanged("state");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int systemCountryId {
            get {
                return this.systemCountryIdField;
            }
            set {
                if ((this.systemCountryIdField.Equals(value) != true)) {
                    this.systemCountryIdField = value;
                    this.RaisePropertyChanged("systemCountryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string zipCode {
            get {
                return this.zipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.zipCodeField, value) != true)) {
                    this.zipCodeField = value;
                    this.RaisePropertyChanged("zipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Addressto", Namespace="http://schemas.datacontract.org/2004/07/ShipCaddieAPIInterface")]
    [System.SerializableAttribute()]
    public partial class Addressto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string address1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string address2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string attentionOfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string companyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string countryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isResidentialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int systemCountryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string zipCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address1 {
            get {
                return this.address1Field;
            }
            set {
                if ((object.ReferenceEquals(this.address1Field, value) != true)) {
                    this.address1Field = value;
                    this.RaisePropertyChanged("address1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address2 {
            get {
                return this.address2Field;
            }
            set {
                if ((object.ReferenceEquals(this.address2Field, value) != true)) {
                    this.address2Field = value;
                    this.RaisePropertyChanged("address2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string attentionOf {
            get {
                return this.attentionOfField;
            }
            set {
                if ((object.ReferenceEquals(this.attentionOfField, value) != true)) {
                    this.attentionOfField = value;
                    this.RaisePropertyChanged("attentionOf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string city {
            get {
                return this.cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cityField, value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string companyName {
            get {
                return this.companyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.companyNameField, value) != true)) {
                    this.companyNameField = value;
                    this.RaisePropertyChanged("companyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string countryCode {
            get {
                return this.countryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.countryCodeField, value) != true)) {
                    this.countryCodeField = value;
                    this.RaisePropertyChanged("countryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isResidential {
            get {
                return this.isResidentialField;
            }
            set {
                if ((this.isResidentialField.Equals(value) != true)) {
                    this.isResidentialField = value;
                    this.RaisePropertyChanged("isResidential");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneNumberField, value) != true)) {
                    this.phoneNumberField = value;
                    this.RaisePropertyChanged("phoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string state {
            get {
                return this.stateField;
            }
            set {
                if ((object.ReferenceEquals(this.stateField, value) != true)) {
                    this.stateField = value;
                    this.RaisePropertyChanged("state");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int systemCountryId {
            get {
                return this.systemCountryIdField;
            }
            set {
                if ((this.systemCountryIdField.Equals(value) != true)) {
                    this.systemCountryIdField = value;
                    this.RaisePropertyChanged("systemCountryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string zipCode {
            get {
                return this.zipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.zipCodeField, value) != true)) {
                    this.zipCodeField = value;
                    this.RaisePropertyChanged("zipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Carrier", Namespace="http://schemas.datacontract.org/2004/07/ShipCaddieAPIInterface")]
    [System.SerializableAttribute()]
    public partial class Carrier : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int carrierClientContractIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int carrierIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int carrierServiceLevelIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int carrierClientContractId {
            get {
                return this.carrierClientContractIdField;
            }
            set {
                if ((this.carrierClientContractIdField.Equals(value) != true)) {
                    this.carrierClientContractIdField = value;
                    this.RaisePropertyChanged("carrierClientContractId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int carrierId {
            get {
                return this.carrierIdField;
            }
            set {
                if ((this.carrierIdField.Equals(value) != true)) {
                    this.carrierIdField = value;
                    this.RaisePropertyChanged("carrierId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int carrierServiceLevelId {
            get {
                return this.carrierServiceLevelIdField;
            }
            set {
                if ((this.carrierServiceLevelIdField.Equals(value) != true)) {
                    this.carrierServiceLevelIdField = value;
                    this.RaisePropertyChanged("carrierServiceLevelId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Package", Namespace="http://schemas.datacontract.org/2004/07/ShipCaddieAPIInterface")]
    [System.SerializableAttribute()]
    public partial class Package : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ShipCaddieApp.ShipCaddieAppXml.Accessorialcharge[] accessorialChargesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ShipCaddieApp.ShipCaddieAppXml.Dimension dimensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ShipCaddieApp.ShipCaddieAppXml.Item[] itemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string referenceField1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string referenceField2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float weightOuncesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float weightPoundsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ShipCaddieApp.ShipCaddieAppXml.Accessorialcharge[] accessorialCharges {
            get {
                return this.accessorialChargesField;
            }
            set {
                if ((object.ReferenceEquals(this.accessorialChargesField, value) != true)) {
                    this.accessorialChargesField = value;
                    this.RaisePropertyChanged("accessorialCharges");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ShipCaddieApp.ShipCaddieAppXml.Dimension dimension {
            get {
                return this.dimensionField;
            }
            set {
                if ((object.ReferenceEquals(this.dimensionField, value) != true)) {
                    this.dimensionField = value;
                    this.RaisePropertyChanged("dimension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ShipCaddieApp.ShipCaddieAppXml.Item[] items {
            get {
                return this.itemsField;
            }
            set {
                if ((object.ReferenceEquals(this.itemsField, value) != true)) {
                    this.itemsField = value;
                    this.RaisePropertyChanged("items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string referenceField1 {
            get {
                return this.referenceField1Field;
            }
            set {
                if ((object.ReferenceEquals(this.referenceField1Field, value) != true)) {
                    this.referenceField1Field = value;
                    this.RaisePropertyChanged("referenceField1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string referenceField2 {
            get {
                return this.referenceField2Field;
            }
            set {
                if ((object.ReferenceEquals(this.referenceField2Field, value) != true)) {
                    this.referenceField2Field = value;
                    this.RaisePropertyChanged("referenceField2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float weightOunces {
            get {
                return this.weightOuncesField;
            }
            set {
                if ((this.weightOuncesField.Equals(value) != true)) {
                    this.weightOuncesField = value;
                    this.RaisePropertyChanged("weightOunces");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float weightPounds {
            get {
                return this.weightPoundsField;
            }
            set {
                if ((this.weightPoundsField.Equals(value) != true)) {
                    this.weightPoundsField = value;
                    this.RaisePropertyChanged("weightPounds");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Dimension", Namespace="http://schemas.datacontract.org/2004/07/ShipCaddieAPIInterface")]
    [System.SerializableAttribute()]
    public partial class Dimension : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int heightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int lengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int widthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int height {
            get {
                return this.heightField;
            }
            set {
                if ((this.heightField.Equals(value) != true)) {
                    this.heightField = value;
                    this.RaisePropertyChanged("height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int length {
            get {
                return this.lengthField;
            }
            set {
                if ((this.lengthField.Equals(value) != true)) {
                    this.lengthField = value;
                    this.RaisePropertyChanged("length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int width {
            get {
                return this.widthField;
            }
            set {
                if ((this.widthField.Equals(value) != true)) {
                    this.widthField = value;
                    this.RaisePropertyChanged("width");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Accessorialcharge", Namespace="http://schemas.datacontract.org/2004/07/ShipCaddieAPIInterface")]
    [System.SerializableAttribute()]
    public partial class Accessorialcharge : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float chargeAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ShipCaddieApp.ShipCaddieAppXml.Input[] inputsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float chargeAmount {
            get {
                return this.chargeAmountField;
            }
            set {
                if ((this.chargeAmountField.Equals(value) != true)) {
                    this.chargeAmountField = value;
                    this.RaisePropertyChanged("chargeAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ShipCaddieApp.ShipCaddieAppXml.Input[] inputs {
            get {
                return this.inputsField;
            }
            set {
                if ((object.ReferenceEquals(this.inputsField, value) != true)) {
                    this.inputsField = value;
                    this.RaisePropertyChanged("inputs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item", Namespace="http://schemas.datacontract.org/2004/07/ShipCaddieAPIInterface")]
    [System.SerializableAttribute()]
    public partial class Item : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ShipCaddieApp.ShipCaddieAppXml.Dimension dimensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string harmonizeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int quantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string skuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float weightOuncesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float weightPoundsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ShipCaddieApp.ShipCaddieAppXml.Dimension dimension {
            get {
                return this.dimensionField;
            }
            set {
                if ((object.ReferenceEquals(this.dimensionField, value) != true)) {
                    this.dimensionField = value;
                    this.RaisePropertyChanged("dimension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string harmonizeCode {
            get {
                return this.harmonizeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.harmonizeCodeField, value) != true)) {
                    this.harmonizeCodeField = value;
                    this.RaisePropertyChanged("harmonizeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int quantity {
            get {
                return this.quantityField;
            }
            set {
                if ((this.quantityField.Equals(value) != true)) {
                    this.quantityField = value;
                    this.RaisePropertyChanged("quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sku {
            get {
                return this.skuField;
            }
            set {
                if ((object.ReferenceEquals(this.skuField, value) != true)) {
                    this.skuField = value;
                    this.RaisePropertyChanged("sku");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float weightOunces {
            get {
                return this.weightOuncesField;
            }
            set {
                if ((this.weightOuncesField.Equals(value) != true)) {
                    this.weightOuncesField = value;
                    this.RaisePropertyChanged("weightOunces");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float weightPounds {
            get {
                return this.weightPoundsField;
            }
            set {
                if ((this.weightPoundsField.Equals(value) != true)) {
                    this.weightPoundsField = value;
                    this.RaisePropertyChanged("weightPounds");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Input", Namespace="http://schemas.datacontract.org/2004/07/ShipCaddieAPIInterface")]
    [System.SerializableAttribute()]
    public partial class Input : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string valueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                if ((object.ReferenceEquals(this.valueField, value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientInformationModel", Namespace="http://schemas.datacontract.org/2004/07/ShipCaddieAPIInterface")]
    [System.SerializableAttribute()]
    public partial class ClientInformationModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string affillateNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int carrierClientContractIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string carrierNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nickNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ShipCaddieApp.ShipCaddieAppXml.Servicelevel[] serviceLevelsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string affillateName {
            get {
                return this.affillateNameField;
            }
            set {
                if ((object.ReferenceEquals(this.affillateNameField, value) != true)) {
                    this.affillateNameField = value;
                    this.RaisePropertyChanged("affillateName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int carrierClientContractId {
            get {
                return this.carrierClientContractIdField;
            }
            set {
                if ((this.carrierClientContractIdField.Equals(value) != true)) {
                    this.carrierClientContractIdField = value;
                    this.RaisePropertyChanged("carrierClientContractId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string carrierName {
            get {
                return this.carrierNameField;
            }
            set {
                if ((object.ReferenceEquals(this.carrierNameField, value) != true)) {
                    this.carrierNameField = value;
                    this.RaisePropertyChanged("carrierName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nickName {
            get {
                return this.nickNameField;
            }
            set {
                if ((object.ReferenceEquals(this.nickNameField, value) != true)) {
                    this.nickNameField = value;
                    this.RaisePropertyChanged("nickName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ShipCaddieApp.ShipCaddieAppXml.Servicelevel[] serviceLevels {
            get {
                return this.serviceLevelsField;
            }
            set {
                if ((object.ReferenceEquals(this.serviceLevelsField, value) != true)) {
                    this.serviceLevelsField = value;
                    this.RaisePropertyChanged("serviceLevels");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Servicelevel", Namespace="http://schemas.datacontract.org/2004/07/ShipCaddieAPIInterface")]
    [System.SerializableAttribute()]
    public partial class Servicelevel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int carrierServiceLevelIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string carrierServiceLevelNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isInternationalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float packageWeightLimitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int carrierServiceLevelId {
            get {
                return this.carrierServiceLevelIdField;
            }
            set {
                if ((this.carrierServiceLevelIdField.Equals(value) != true)) {
                    this.carrierServiceLevelIdField = value;
                    this.RaisePropertyChanged("carrierServiceLevelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string carrierServiceLevelName {
            get {
                return this.carrierServiceLevelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.carrierServiceLevelNameField, value) != true)) {
                    this.carrierServiceLevelNameField = value;
                    this.RaisePropertyChanged("carrierServiceLevelName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isInternational {
            get {
                return this.isInternationalField;
            }
            set {
                if ((this.isInternationalField.Equals(value) != true)) {
                    this.isInternationalField = value;
                    this.RaisePropertyChanged("isInternational");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float packageWeightLimit {
            get {
                return this.packageWeightLimitField;
            }
            set {
                if ((this.packageWeightLimitField.Equals(value) != true)) {
                    this.packageWeightLimitField = value;
                    this.RaisePropertyChanged("packageWeightLimit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemCountryModel", Namespace="http://schemas.datacontract.org/2004/07/ShipCaddieAPIInterface")]
    [System.SerializableAttribute()]
    public partial class SystemCountryModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string alpha2CodeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int countryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string countryNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string alpha2CodeName {
            get {
                return this.alpha2CodeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.alpha2CodeNameField, value) != true)) {
                    this.alpha2CodeNameField = value;
                    this.RaisePropertyChanged("alpha2CodeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int countryId {
            get {
                return this.countryIdField;
            }
            set {
                if ((this.countryIdField.Equals(value) != true)) {
                    this.countryIdField = value;
                    this.RaisePropertyChanged("countryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string countryName {
            get {
                return this.countryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.countryNameField, value) != true)) {
                    this.countryNameField = value;
                    this.RaisePropertyChanged("countryName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrintRequestModel", Namespace="http://schemas.datacontract.org/2004/07/ShipCaddieAPIInterface")]
    [System.SerializableAttribute()]
    public partial class PrintRequestModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ShipCaddieApp.ShipCaddieAppXml.Datablock[] dataBlocksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] flagsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string printTemplateTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ShipCaddieApp.ShipCaddieAppXml.Datablock[] dataBlocks {
            get {
                return this.dataBlocksField;
            }
            set {
                if ((object.ReferenceEquals(this.dataBlocksField, value) != true)) {
                    this.dataBlocksField = value;
                    this.RaisePropertyChanged("dataBlocks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] flags {
            get {
                return this.flagsField;
            }
            set {
                if ((object.ReferenceEquals(this.flagsField, value) != true)) {
                    this.flagsField = value;
                    this.RaisePropertyChanged("flags");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string printTemplateType {
            get {
                return this.printTemplateTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.printTemplateTypeField, value) != true)) {
                    this.printTemplateTypeField = value;
                    this.RaisePropertyChanged("printTemplateType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Datablock", Namespace="http://schemas.datacontract.org/2004/07/ShipCaddieAPIInterface")]
    [System.SerializableAttribute()]
    public partial class Datablock : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dataSourceNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string labelKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string trackingNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dataSourceName {
            get {
                return this.dataSourceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.dataSourceNameField, value) != true)) {
                    this.dataSourceNameField = value;
                    this.RaisePropertyChanged("dataSourceName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string labelKey {
            get {
                return this.labelKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.labelKeyField, value) != true)) {
                    this.labelKeyField = value;
                    this.RaisePropertyChanged("labelKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string trackingNumber {
            get {
                return this.trackingNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.trackingNumberField, value) != true)) {
                    this.trackingNumberField = value;
                    this.RaisePropertyChanged("trackingNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenModel", Namespace="http://schemas.datacontract.org/2004/07/ShipCaddieAPIInterface")]
    [System.SerializableAttribute()]
    public partial class TokenModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string access_tokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string refreshExpiresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string refreshIssuedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string refresh_tokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tokenExpiresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tokenIssuedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string token_typeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string access_token {
            get {
                return this.access_tokenField;
            }
            set {
                if ((object.ReferenceEquals(this.access_tokenField, value) != true)) {
                    this.access_tokenField = value;
                    this.RaisePropertyChanged("access_token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string refreshExpires {
            get {
                return this.refreshExpiresField;
            }
            set {
                if ((object.ReferenceEquals(this.refreshExpiresField, value) != true)) {
                    this.refreshExpiresField = value;
                    this.RaisePropertyChanged("refreshExpires");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string refreshIssued {
            get {
                return this.refreshIssuedField;
            }
            set {
                if ((object.ReferenceEquals(this.refreshIssuedField, value) != true)) {
                    this.refreshIssuedField = value;
                    this.RaisePropertyChanged("refreshIssued");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string refresh_token {
            get {
                return this.refresh_tokenField;
            }
            set {
                if ((object.ReferenceEquals(this.refresh_tokenField, value) != true)) {
                    this.refresh_tokenField = value;
                    this.RaisePropertyChanged("refresh_token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tokenExpires {
            get {
                return this.tokenExpiresField;
            }
            set {
                if ((object.ReferenceEquals(this.tokenExpiresField, value) != true)) {
                    this.tokenExpiresField = value;
                    this.RaisePropertyChanged("tokenExpires");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tokenIssued {
            get {
                return this.tokenIssuedField;
            }
            set {
                if ((object.ReferenceEquals(this.tokenIssuedField, value) != true)) {
                    this.tokenIssuedField = value;
                    this.RaisePropertyChanged("tokenIssued");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string token_type {
            get {
                return this.token_typeField;
            }
            set {
                if ((object.ReferenceEquals(this.token_typeField, value) != true)) {
                    this.token_typeField = value;
                    this.RaisePropertyChanged("token_type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VoidLabelModel", Namespace="http://schemas.datacontract.org/2004/07/ShipCaddieAPIInterface")]
    [System.SerializableAttribute()]
    public partial class VoidLabelModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ShipCaddieApp.ShipCaddieAppXml.TrackingNumber[] TrackingNumberListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ShipCaddieApp.ShipCaddieAppXml.TrackingNumber[] TrackingNumberList {
            get {
                return this.TrackingNumberListField;
            }
            set {
                if ((object.ReferenceEquals(this.TrackingNumberListField, value) != true)) {
                    this.TrackingNumberListField = value;
                    this.RaisePropertyChanged("TrackingNumberList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrackingNumber", Namespace="http://schemas.datacontract.org/2004/07/ShipCaddieAPIInterface")]
    [System.SerializableAttribute()]
    public partial class TrackingNumber : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string trackingNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string trackingNumber {
            get {
                return this.trackingNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.trackingNumberField, value) != true)) {
                    this.trackingNumberField = value;
                    this.RaisePropertyChanged("trackingNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ShipCaddieAppXml.IShipCaddieAPI")]
    public interface IShipCaddieAPI {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShipCaddieAPI/AddShipment", ReplyAction="http://tempuri.org/IShipCaddieAPI/AddShipmentResponse")]
        ShipCaddieApp.ShipCaddieAppXml.ShipmentModelIntegration AddShipment(string Token, ShipCaddieApp.ShipCaddieAppXml.ShipmentModelIntegration Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShipCaddieAPI/AddShipment", ReplyAction="http://tempuri.org/IShipCaddieAPI/AddShipmentResponse")]
        System.Threading.Tasks.Task<ShipCaddieApp.ShipCaddieAppXml.ShipmentModelIntegration> AddShipmentAsync(string Token, ShipCaddieApp.ShipCaddieAppXml.ShipmentModelIntegration Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShipCaddieAPI/GetClientContractInformation", ReplyAction="http://tempuri.org/IShipCaddieAPI/GetClientContractInformationResponse")]
        ShipCaddieApp.ShipCaddieAppXml.ClientInformationModel[] GetClientContractInformation(string Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShipCaddieAPI/GetClientContractInformation", ReplyAction="http://tempuri.org/IShipCaddieAPI/GetClientContractInformationResponse")]
        System.Threading.Tasks.Task<ShipCaddieApp.ShipCaddieAppXml.ClientInformationModel[]> GetClientContractInformationAsync(string Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShipCaddieAPI/GetCountrySystemInformation", ReplyAction="http://tempuri.org/IShipCaddieAPI/GetCountrySystemInformationResponse")]
        ShipCaddieApp.ShipCaddieAppXml.SystemCountryModel[] GetCountrySystemInformation(string Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShipCaddieAPI/GetCountrySystemInformation", ReplyAction="http://tempuri.org/IShipCaddieAPI/GetCountrySystemInformationResponse")]
        System.Threading.Tasks.Task<ShipCaddieApp.ShipCaddieAppXml.SystemCountryModel[]> GetCountrySystemInformationAsync(string Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShipCaddieAPI/GetLabels", ReplyAction="http://tempuri.org/IShipCaddieAPI/GetLabelsResponse")]
        ShipCaddieApp.ShipCaddieAppXml.PrintRequestModel[] GetLabels(string Token, ShipCaddieApp.ShipCaddieAppXml.ShipmentModelIntegration Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShipCaddieAPI/GetLabels", ReplyAction="http://tempuri.org/IShipCaddieAPI/GetLabelsResponse")]
        System.Threading.Tasks.Task<ShipCaddieApp.ShipCaddieAppXml.PrintRequestModel[]> GetLabelsAsync(string Token, ShipCaddieApp.ShipCaddieAppXml.ShipmentModelIntegration Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShipCaddieAPI/GetRate", ReplyAction="http://tempuri.org/IShipCaddieAPI/GetRateResponse")]
        ShipCaddieApp.ShipCaddieAppXml.ShipmentModelIntegration GetRate(string Token, ShipCaddieApp.ShipCaddieAppXml.ShipmentModelIntegration Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShipCaddieAPI/GetRate", ReplyAction="http://tempuri.org/IShipCaddieAPI/GetRateResponse")]
        System.Threading.Tasks.Task<ShipCaddieApp.ShipCaddieAppXml.ShipmentModelIntegration> GetRateAsync(string Token, ShipCaddieApp.ShipCaddieAppXml.ShipmentModelIntegration Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShipCaddieAPI/GetToken", ReplyAction="http://tempuri.org/IShipCaddieAPI/GetTokenResponse")]
        ShipCaddieApp.ShipCaddieAppXml.TokenModel GetToken(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShipCaddieAPI/GetToken", ReplyAction="http://tempuri.org/IShipCaddieAPI/GetTokenResponse")]
        System.Threading.Tasks.Task<ShipCaddieApp.ShipCaddieAppXml.TokenModel> GetTokenAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShipCaddieAPI/RefreshToken", ReplyAction="http://tempuri.org/IShipCaddieAPI/RefreshTokenResponse")]
        ShipCaddieApp.ShipCaddieAppXml.TokenModel RefreshToken(string Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShipCaddieAPI/RefreshToken", ReplyAction="http://tempuri.org/IShipCaddieAPI/RefreshTokenResponse")]
        System.Threading.Tasks.Task<ShipCaddieApp.ShipCaddieAppXml.TokenModel> RefreshTokenAsync(string Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShipCaddieAPI/VoidLabel", ReplyAction="http://tempuri.org/IShipCaddieAPI/VoidLabelResponse")]
        ShipCaddieApp.ShipCaddieAppXml.VoidLabelModel[] VoidLabel(string Token, string labelKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShipCaddieAPI/VoidLabel", ReplyAction="http://tempuri.org/IShipCaddieAPI/VoidLabelResponse")]
        System.Threading.Tasks.Task<ShipCaddieApp.ShipCaddieAppXml.VoidLabelModel[]> VoidLabelAsync(string Token, string labelKey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IShipCaddieAPIChannel : ShipCaddieApp.ShipCaddieAppXml.IShipCaddieAPI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShipCaddieAPIClient : System.ServiceModel.ClientBase<ShipCaddieApp.ShipCaddieAppXml.IShipCaddieAPI>, ShipCaddieApp.ShipCaddieAppXml.IShipCaddieAPI {
        
        public ShipCaddieAPIClient() {
        }
        
        public ShipCaddieAPIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShipCaddieAPIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShipCaddieAPIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShipCaddieAPIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ShipCaddieApp.ShipCaddieAppXml.ShipmentModelIntegration AddShipment(string Token, ShipCaddieApp.ShipCaddieAppXml.ShipmentModelIntegration Request) {
            return base.Channel.AddShipment(Token, Request);
        }
        
        public System.Threading.Tasks.Task<ShipCaddieApp.ShipCaddieAppXml.ShipmentModelIntegration> AddShipmentAsync(string Token, ShipCaddieApp.ShipCaddieAppXml.ShipmentModelIntegration Request) {
            return base.Channel.AddShipmentAsync(Token, Request);
        }
        
        public ShipCaddieApp.ShipCaddieAppXml.ClientInformationModel[] GetClientContractInformation(string Token) {
            return base.Channel.GetClientContractInformation(Token);
        }
        
        public System.Threading.Tasks.Task<ShipCaddieApp.ShipCaddieAppXml.ClientInformationModel[]> GetClientContractInformationAsync(string Token) {
            return base.Channel.GetClientContractInformationAsync(Token);
        }
        
        public ShipCaddieApp.ShipCaddieAppXml.SystemCountryModel[] GetCountrySystemInformation(string Token) {
            return base.Channel.GetCountrySystemInformation(Token);
        }
        
        public System.Threading.Tasks.Task<ShipCaddieApp.ShipCaddieAppXml.SystemCountryModel[]> GetCountrySystemInformationAsync(string Token) {
            return base.Channel.GetCountrySystemInformationAsync(Token);
        }
        
        public ShipCaddieApp.ShipCaddieAppXml.PrintRequestModel[] GetLabels(string Token, ShipCaddieApp.ShipCaddieAppXml.ShipmentModelIntegration Request) {
            return base.Channel.GetLabels(Token, Request);
        }
        
        public System.Threading.Tasks.Task<ShipCaddieApp.ShipCaddieAppXml.PrintRequestModel[]> GetLabelsAsync(string Token, ShipCaddieApp.ShipCaddieAppXml.ShipmentModelIntegration Request) {
            return base.Channel.GetLabelsAsync(Token, Request);
        }
        
        public ShipCaddieApp.ShipCaddieAppXml.ShipmentModelIntegration GetRate(string Token, ShipCaddieApp.ShipCaddieAppXml.ShipmentModelIntegration Request) {
            return base.Channel.GetRate(Token, Request);
        }
        
        public System.Threading.Tasks.Task<ShipCaddieApp.ShipCaddieAppXml.ShipmentModelIntegration> GetRateAsync(string Token, ShipCaddieApp.ShipCaddieAppXml.ShipmentModelIntegration Request) {
            return base.Channel.GetRateAsync(Token, Request);
        }
        
        public ShipCaddieApp.ShipCaddieAppXml.TokenModel GetToken(string username, string password) {
            return base.Channel.GetToken(username, password);
        }
        
        public System.Threading.Tasks.Task<ShipCaddieApp.ShipCaddieAppXml.TokenModel> GetTokenAsync(string username, string password) {
            return base.Channel.GetTokenAsync(username, password);
        }
        
        public ShipCaddieApp.ShipCaddieAppXml.TokenModel RefreshToken(string Token) {
            return base.Channel.RefreshToken(Token);
        }
        
        public System.Threading.Tasks.Task<ShipCaddieApp.ShipCaddieAppXml.TokenModel> RefreshTokenAsync(string Token) {
            return base.Channel.RefreshTokenAsync(Token);
        }
        
        public ShipCaddieApp.ShipCaddieAppXml.VoidLabelModel[] VoidLabel(string Token, string labelKey) {
            return base.Channel.VoidLabel(Token, labelKey);
        }
        
        public System.Threading.Tasks.Task<ShipCaddieApp.ShipCaddieAppXml.VoidLabelModel[]> VoidLabelAsync(string Token, string labelKey) {
            return base.Channel.VoidLabelAsync(Token, labelKey);
        }
    }
}
